In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
from google.colab import files
import datetime

In [ ]:
df=pd.read_csv('Book2.csv')

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
df=df.drop(['Unnamed: 9', 'Unnamed: 10','Unnamed: 11','Unnamed: 12'], axis=1)

In [ ]:
df

,Physician_ID,Week,Sum of Market_Rx,Sum of Brand_Rx,Sum of Emails_Delivered,Sum of YD Email,Sum of Samples_Dropped,Sum of YD Sample,Sum of Sales_Rep_Calls
0,6977,1.0,9.002623e+01,25.361,0,0,10,1,1
1,6977,2.0,7.166429e+01,21.422,0,0,6,1,1
2,6977,3.0,1.887062e+02,64.093,0,0,0,0,1
3,6977,4.0,1.412869e+02,44.893,0,0,8,1,1
4,6977,5.0,1.163748e+02,38.270,0,0,6,1,1
...,...,...,...,...,...,...,...,...,...
569996,180,54.0,2.214408e+01,0.000,0,0,0,0,0
569997,180,55.0,1.568808e+01,0.000,0,0,0,0,0
569998,180,56.0,2.276278e+01,0.000,0,0,0,0,0
569999,180,57.0,2.407012e+01,0.000,0,0,0,0,0
570000,Grand Total,NaN,4.553701e+06,389212.053,154569,97929,493460,58576,223037

In [ ]:

final_score=[]

In [ ]:
for i in range(2,3):
  #a1=[];b1=[];c1=[]
  #a=[];b=[];c=[]
  df2=df.iloc[(57*(i-1)):i*57]
df2

,Physician_ID,Week,Sum of Market_Rx,Sum of Brand_Rx,Sum of Emails_Delivered,Sum of YD Email,Sum of Samples_Dropped,Sum of YD Sample,Sum of Sales_Rep_Calls
57,1964,1.0,62.54788,12.737,0,0,0,0,0
58,1964,2.0,63.44096,15.003,0,0,6,1,1
59,1964,3.0,84.53056,25.243,0,0,0,0,1
60,1964,4.0,54.44291,14.126,0,0,18,1,1
61,1964,5.0,35.63712,10.615,0,0,10,1,1
62,1964,6.0,50.37025,11.698,0,0,0,0,1
63,1964,7.0,82.66639,17.261,0,0,10,1,1
64,1964,8.0,66.37575,19.758,0,0,12,1,1
65,1964,9.0,46.98085,15.282,0,0,14,1,1
66,1964,10.0,57.41267,14.158,0,0,4,1,1
67,1964,11.0,81.11157,25.852,0,0,14,1,1
68,1964,12.0,90.83054,28.399,0,0,12,1,1
69,1964,13.0,60.34208,21.525,0,0,14,1,1
70,1964,14.0,49.73810,9.975,0,0,28,1,1
71,1964,15.0,57.68167,14.216,0,0,0,0,1
72,1964,16.0,66.28429,19.678,0,0,0,0,1
73,1964,17.0,24.88250,8.192,0,0,48,1,1
74,1964,18.0,80.77532,16.346,0,0,31,1,1
75,1964,19.0,48.72397,11.040,0,0,0,0,1
76,1964,20.0,69.99649,18.632,0,0,9,1,1
77,1964,21.0,42.91088,8.145,0,0,0,0,1
78,1964,22.0,20.02167,5.284,0,0,0,0,1
79,1964,23.0,24.25035,7.159,0,0,0,0,0
80,1964,24.0,77.39668,18.274,0,0,15,1,1
81,1964,25.0,40.73467,9.000,0,0,0,0,1
82,1964,26.0,38.03929,10.431,0,0,5,1,1
83,1964,27.0,35.09643,6.970,0,0,4,1,1
84,1964,28.0,76.61927,17.142,0,0,19,1,1
85,1964,29.0,57.21899,13.359,0,0,0,0,1
86,1964,30.0,22.29741,7.209,0,0,6,1,1
87,1964,31.0,51.99501,11.519,0,0,6,1,1
88,1964,32.0,78.81700,14.058,0,0,0,0,1
89,1964,33.0,46.60963,8.966,0,0,8,1,1
90,1964,34.0,33.84558,7.271,0,0,6,1,1
91,1964,35.0,71.31997,13.839,0,0,9,1,1
92,1964,36.0,58.63662,9.527,0,0,0,0,1
93,1964,37.0,94.30064,15.416,0,0,11,1,1
94,1964,38.0,54.79530,10.198,0,0,0,0,1
95,1964,39.0,69.89158,17.087,0,0,0,0,1
96,1964,40.0,65.95342,10.400,0,0,12,1,1
97,1964,41.0,85.42902,15.348,0,0,28,1,1
98,1964,42.0,52.78318,8.110,0,0,22,1,1
99,1964,43.0,57.82693,13.035,0,0,26,1,1
100,1964,44.0,80.44445,8.093,0,0,4,1,1
101,1964,45.0,63.94668,15.496,0,0,0,0,1
102,1964,46.0,48.72935,5.975,0,0,12,1,1
103,1964,47.0,76.04630,15.293,0,0,6,1,1
104,1964,48.0,54.96208,11.201,0,0,12,1,1
105,1964,49.0,74.13102,19.075,0,0,9,1,1
106,1964,50.0,72.22381,15.511,0,0,10,1,1
107,1964,51.0,65.21367,15.061,0,0,16,1,1
108,1964,52.0,27.15555,8.133,0,0,0,0,0
109,1964,53.0,48.38772,10.171,0,0,0,0,0
110,1964,54.0,98.09892,19.907,0,0,0,0,1
111,1964,55.0,107.05662,21.999,0,0,22,1,1
112,1964,56.0,83.11562,18.337,0,0,0,0,1
113,1964,57.0,97.82454,20.427,0,0,18,1,1

In [ ]:
for i in range(1,10001):
  a1=[];b1=[];c1=[]
  #a=[];b=[];c=[]
  df2=df.iloc[(57*(i-1)):i*57]
  k=df2['Sum of Brand_Rx'].tolist()
  a=df2['Sum of YD Email'].tolist()
  b=df2['Sum of YD Sample'].tolist()
  c=df2['Sum of Sales_Rep_Calls'].tolist()
  for j in range(len(k)):
    
    if(a[j]==0):
      a1.append(0)
    else:
      a1.append(k[j])

    if(b[j]==0):
      b1.append(0)
    else:
      b1.append(k[j])
    
    if(c[j]==0):
      c1.append(0)
    else:
      c1.append(k[j])
  total1=sum(a1)
  total2=sum(b1)
  total3=sum(c1)
  
  temp=[total1,total2,total3]
  maxpos = temp.index(max(temp))
  if(sum(temp)==0):
    maxpos=0
  final_score.append(maxpos+1)





df2

,Physician_ID,Week,Sum of Market_Rx,Sum of Brand_Rx,Sum of Emails_Delivered,Sum of YD Email,Sum of Samples_Dropped,Sum of YD Sample,Sum of Sales_Rep_Calls
569943,180,1.0,9.79698,0.0,0,0,0,0,0
569944,180,2.0,17.28325,0.0,0,0,6,1,1
569945,180,3.0,21.53076,0.0,0,0,0,0,0
569946,180,4.0,3.24145,0.0,0,0,0,0,0
569947,180,5.0,5.70011,0.0,0,0,0,0,0
569948,180,6.0,5.69204,0.0,1,1,0,0,0
569949,180,7.0,12.18570,0.0,1,1,0,0,0
569950,180,8.0,5.43918,0.0,0,0,0,0,0
569951,180,9.0,3.27373,0.0,0,0,0,0,0
569952,180,10.0,9.23746,0.0,1,1,0,0,0
569953,180,11.0,12.60534,0.0,1,1,0,0,0
569954,180,12.0,9.07606,0.0,0,0,0,0,0
569955,180,13.0,6.89178,0.0,2,1,0,0,0
569956,180,14.0,6.43986,0.0,1,1,0,0,0
569957,180,15.0,9.31278,0.0,0,0,0,0,0
569958,180,16.0,6.04981,0.0,1,1,0,0,0
569959,180,17.0,19.53747,0.0,0,0,0,0,0
569960,180,18.0,3.21455,0.0,0,0,0,0,0
569961,180,19.0,12.05658,0.0,0,0,0,0,0
569962,180,20.0,12.42511,0.0,4,1,0,0,0
569963,180,21.0,9.33430,0.0,0,0,0,0,0
569964,180,22.0,8.61069,0.0,0,0,0,0,0
569965,180,23.0,2.94017,0.0,0,0,0,0,0
569966,180,24.0,12.38207,0.0,0,0,0,0,0
569967,180,25.0,12.11576,0.0,0,0,0,0,0
569968,180,26.0,11.99202,0.0,0,0,0,0,0
569969,180,27.0,0.00000,0.0,0,0,0,0,0
569970,180,28.0,9.87230,0.0,0,0,0,0,0
569971,180,29.0,13.56567,0.0,0,0,0,0,0
569972,180,30.0,12.86089,0.0,0,0,0,0,0
569973,180,31.0,2.74918,0.0,0,0,0,0,0
569974,180,32.0,6.53132,0.0,2,1,0,0,0
569975,180,33.0,17.36933,0.0,0,0,0,0,0
569976,180,34.0,13.02767,0.0,0,0,0,0,0
569977,180,35.0,22.40770,0.0,0,0,0,0,0
569978,180,36.0,3.02087,0.0,0,0,0,0,0
569979,180,37.0,16.01088,0.0,0,0,0,0,0
569980,180,38.0,6.57974,0.0,0,0,0,0,0
569981,180,39.0,15.48633,0.0,0,0,0,0,0
569982,180,40.0,15.45136,0.0,1,1,0,0,0
569983,180,41.0,9.19711,0.0,0,0,0,0,0
569984,180,42.0,3.24414,0.0,0,0,0,0,0
569985,180,43.0,32.52748,0.0,0,0,0,0,0
569986,180,44.0,9.47418,0.0,0,0,0,0,0
569987,180,45.0,6.02022,0.0,1,1,0,0,0
569988,180,46.0,9.22401,0.0,0,0,0,0,0
569989,180,47.0,13.58719,0.0,0,0,0,0,0
569990,180,48.0,8.97115,0.0,0,0,0,0,0
569991,180,49.0,21.20796,0.0,0,0,0,0,0
569992,180,50.0,12.36593,0.0,0,0,0,0,0
569993,180,51.0,13.20790,0.0,0,0,0,0,0
569994,180,52.0,14.04180,0.0,0,0,0,0,0
569995,180,53.0,15.63159,0.0,0,0,0,0,0
569996,180,54.0,22.14408,0.0,0,0,0,0,0
569997,180,55.0,15.68808,0.0,0,0,0,0,0
569998,180,56.0,22.76278,0.0,0,0,0,0,0
569999,180,57.0,24.07012,0.0,0,0,0,0,0

In [ ]:
df3 = pd.DataFrame(final_score)

In [ ]:
print(len(final_score))

10000

In [ ]:
final_score[0]

3

In [ ]:
df3.to_csv('file3.csv')

In [ ]:
df.iloc[113]

Physician_ID                   1964
Week                           57.0
Sum of Market_Rx           97.82454
Sum of Brand_Rx              20.427
Sum of Emails_Delivered           0
Sum of YD Email                   0
Sum of Samples_Dropped           18
Sum of YD Sample                  1
Sum of Sales_Rep_Calls            1
Name: 113, dtype: object

In [ ]:
k=[]
l=df['Physician_ID'].tolist()
for i in range(10000):
  k.append(l[57*i])

In [ ]:
print(len(k))

10000

In [ ]:
df4 = pd.DataFrame(k)

In [ ]:
df4.to_csv('file2.csv')

In [ ]:
l

(6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 6977,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1964,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 1951,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 5974,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1329,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 1257,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 7974,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5939,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 5419,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 4416,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 109,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 6476,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4647,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 4546,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 8369,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 7815,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 3761,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 7617,
 ...)